import { FileSystemPort, ProjectFile } from '../../core/ports/file-system.port.js';
import { StackRecommendation } from '../../core/models/recommendation.js';
import fs from 'fs/promises';
import path from 'path';
import yaml from 'js-yaml';

export class NodeFileSystemAdapter implements FileSystemPort {
  async readBrief(filePath: string): Promise<unknown> {
    const absolutePath = path.resolve(filePath);
    const content = await fs.readFile(absolutePath, 'utf8');
    
    // Support JSON parsing if filename ends in .json, otherwise YAML
    if (filePath.endsWith('.json')) {
      return JSON.parse(content);
    }
    
    return yaml.load(content);
  }

  async directoryExists(dirPath: string): Promise<boolean> {
    try {
      const stats = await fs.stat(dirPath);
      return stats.isDirectory();
    } catch {
      return false;
    }
  }

  async writeOutputs(
    recommendation: StackRecommendation,
    projectRoot: string
  ): Promise<{ yamlPath: string; mdPath: string }> {
    const stackDir = path.join(projectRoot, '.stack');
    await fs.mkdir(stackDir, { recursive: true });

    // 1. Prepare Content
    const yamlContent = yaml.dump(recommendation, {
      indent: 2,
      noRefs: true,
      lineWidth: -1
    });
    const mdContent = this.generateMarkdown(recommendation);

    // 2. Write to .stack
    const yamlPath = path.join(stackDir, 'stack.yaml');
    const mdPath = path.join(stackDir, 'README.md');
    await fs.writeFile(yamlPath, `# Generated by dotstack\n` + yamlContent, 'utf8');
    await fs.writeFile(mdPath, mdContent, 'utf8');

    // 3. Write to .context/dotstack if exists
    const contextDir = path.join(projectRoot, '.context');
    const hasContext = await this.directoryExists(contextDir);
    if (hasContext) {
      const contextDotstackDir = path.join(contextDir, 'dotstack');
      await fs.mkdir(contextDotstackDir, { recursive: true });
      await fs.writeFile(path.join(contextDotstackDir, 'stack.yaml'), `# Generated by dotstack\n` + yamlContent, 'utf8');
      await fs.writeFile(path.join(contextDotstackDir, 'README.md'), mdContent, 'utf8');
    }

    return { yamlPath, mdPath };
  }

  private generateMarkdown(rec: StackRecommendation): string {
    const r = rec.recommendation;
    const rat = rec.rationale;

    let md = `# Recommended Architecture: ${r.architectureStyle}\n\n`;
    md += `This repository technology stack was recommended by **dotstack**.\n\n`;

    // Tech Stack Table
    md += `## Technology Stack Summary\n\n`;
    md += `| Component | Selected Technology | Rationale |\n`;
    md += `| :--- | :--- | :--- |\n`;
    md += `| **Architecture Style** | ${r.architectureStyle} | ${rat.architectureStyle} |\n`;
    md += `| **Frontend Framework** | ${r.frontend} | ${rat.frontend} |\n`;
    md += `| **Backend Framework** | ${r.backend} | ${rat.backend} |\n`;
    md += `| **Database** | ${r.database} | ${rat.database} |\n`;
    if (r.cache) {
      md += `| **Caching Tier** | ${r.cache} | ${rat.cache || ''} |\n`;
    }
    if (r.aiFramework) {
      md += `| **AI Orchestration** | ${r.aiFramework} | ${rat.aiFramework || ''} |\n`;
    }
    md += `| **Deployment Target** | ${r.deployment} | ${rat.deployment} |\n\n`;

    // Risks & Warnings Section
    if (rec.risks.length > 0) {
      md += `## Architectural Risks & Warnings\n\n`;
      for (const risk of rec.risks) {
        md += `> [!WARNING]\n`;
        md += `> **${risk}**\n\n`;
      }
    }

    // Design Patterns
    md += `## Design Patterns & Ecosystem References\n\n`;
    md += `To maintain code quality and architectural integrity, the following patterns are recommended for this stack:\n\n`;

    for (const pattern of rec.patterns) {
      md += `### 1. ${pattern.name}\n`;
      md += `${pattern.description}\n\n`;
      if (pattern.referenceUrl) {
        md += `- **Reference Docs**: [GitHub Topic / RefactoringGuru](${pattern.referenceUrl})\n`;
      }
      
      if (pattern.examples.length > 0) {
        md += `- **Reference Repositories**:\n`;
        for (const ex of pattern.examples) {
          md += `  - [${ex.name}](${ex.url}) ${ex.description ? `- ${ex.description}` : ''}\n`;
        }
      }
      md += `\n`;
    }

    md += `---\n`;
    md += `*Generated automatically by dotstack on ${new Date(rec.metadata.generatedAt).toLocaleDateString()}.*\n`;

    return md;
  }

  async getFilesRecursively(projectRoot: string): Promise<ProjectFile[]> {
    const files: ProjectFile[] = [];
    const ignoreDirs = new Set([
      '.git', 'node_modules', 'dist', '.stack', '.context/dotstack',
      'coverage', '.release', '.gemini', '.system_generated'
    ]);
    const readableExtensions = new Set([
      '.ts', '.js', '.json', '.yaml', '.yml', '.md', '.py', '.go', '.java',
      '.tf', '.css', '.html', '.sh', '.bat', '.toml', '.xml', '.sql', '.graphql',
      '.hcl', '.prisma', '.proto'
    ]);

    const walk = async (currentDir: string) => {
      const entries = await fs.readdir(currentDir, { withFileTypes: true });
      for (const entry of entries) {
        const fullPath = path.join(currentDir, entry.name);
        const relativePath = path.relative(projectRoot, fullPath);

        const segments = relativePath.split(path.sep);
        const shouldIgnore = segments.some(seg => ignoreDirs.has(seg));
        if (shouldIgnore) {
          continue;
        }

        if (entry.isDirectory()) {
          await walk(fullPath);
        } else if (entry.isFile()) {
          const ext = path.extname(entry.name).toLowerCase();
          const lowerName = entry.name.toLowerCase();
          const isReadable =
            readableExtensions.has(ext) ||
            lowerName === 'dockerfile' ||
            lowerName === 'makefile' ||
            lowerName === 'justfile' ||
            lowerName === '.env.example';

          if (isReadable) {
            try {
              const content = await fs.readFile(fullPath, 'utf8');
              files.push({
                relativePath: relativePath.replace(/\\/g, '/'),
                content
              });
            } catch {
              // skip unreadable files
            }
          }
        }
      }
    };

    try {
      await walk(projectRoot);
    } catch {
      // ignore walk errors
    }
    return files;
  }
}
